apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  username: 'guest'
  password: 'guest'
  uri: 'amqp://guest:guest@rabbitmq:5672/'
---
apiVersion: v1
kind: Secret
metadata:
  name: external-apis
type: Opaque
stringData:
  osrm: 'https://osrm.selfmadeengineer.com'

---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
type: Opaque
stringData:
  stripe-secret-key: 'sk_test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  stripe-webhook-key: 'sk_test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
